services:
  - type: web
    name: smart-email-assistant-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    region: singapore
    plan: free
    healthCheckPath: /api/email/health

    envVars:
      - key: SPRING_AI_GOOGLE_GENAI_API_KEY
        sync: false