package com.smartemail.controller;

import com.smartemail.dto.EmailRequest;
import com.smartemail.service.EmailService;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.tags.Tag;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

/**
 * REST controller exposing the AI email reply generation endpoint.
 *
 * <p>Base path: {@code /api/email}
 */
@Tag(name = "Email Assistant", description = "AI-powered email reply generation via Spring AI + Gemini")
@RestController
@RequestMapping("/api/email")
@CrossOrigin(origins = "*")
public class EmailController {

    private final EmailService emailService;

    public EmailController(EmailService emailService) {
        this.emailService = emailService;
    }

    /**
     * Generate an AI-powered email reply.
     *
     * <p>POST /api/email/generate
     *
     * <p>Request body (all fields except emailContent are optional):
     * <pre>
     * {
     *   "sender":            "hr@company.com",
     *   "subject":           "Interview Invitation",
     *   "emailContent":      "Hi, we'd like to invite you for an interview...",
     *   "responseApproach":  "ACCEPT",
     *   "tone":              "professional",
     *   "customInstruction": "Mention that I'm available Monday or Tuesday only."
     * }
     * </pre>
     *
     * <p>Defaults applied by the service when fields are absent:
     * <ul>
     *   <li>responseApproach → NEUTRAL (balanced response)</li>
     *   <li>tone             → professional</li>
     *   <li>sender           → Unknown Sender</li>
     *   <li>subject          → No Subject</li>
     * </ul>
     *
     * @param emailRequest the enriched request payload
     * @return a plain-text email reply generated by Gemini
     */
    /**
     * Health check endpoint for deployment (Render/Kubernetes monitoring).
     *
     * <p>GET /api/email/health
     */
    @Operation(summary = "Backend health check", description = "Returns service status for Render monitoring")
    @GetMapping("/health")
    public ResponseEntity<String> healthCheck() {
        return ResponseEntity.ok("UP");
    }

    @Operation(
        summary = "Generate AI email reply",
        description = "Accepts email context (sender, subject, body, approach, tone) and returns an AI-generated reply."
    )
    @PostMapping(value = "/generate", produces = MediaType.TEXT_PLAIN_VALUE)
    public ResponseEntity<String> generateEmailReply(@RequestBody EmailRequest emailRequest) {
        String reply = emailService.generateEmailReply(emailRequest);
        return ResponseEntity.ok(reply);
    }
}
